version: '3'

services:
  compute:
    image: chelsea486mhz/stargazer-compute
    restart: unless-stopped
    depends_on:
      - auth
      - manager
    environment:
      AUTH_ENDPOINT: 'http://auth:5000'
      MANAGER_ENDPOINT: 'http://manager:5000'
      TOKEN: 'Kq5AfYtpYkcGbPnm0z2I_SIRGRem-zKmXA5rnPguUIB7y2DNQTW1KIYouV9IaHH6'

  auth:
    image: chelsea486mhz/stargazer-auth
    restart: unless-stopped
    environment:
      USER_TOKEN: 'DrERUGbWdDltQmkii0Mswney_dgDnUKFAwMC-TYB-C2zMnOuQeHgPtsHhBWzgoIg'

  manager:
    image: chelsea486mhz/stargazer-manager
    restart: unless-stopped
    depends_on:
      - auth
    environment:
      AUTH_ENDPOINT: 'http://auth:5000'
      TOKEN: '3gEy0rWMRqXfJw9aLKzzSuhXggxGTLL4bYsTt-VdmFcmOWQ_ZCwTswvZM6kNVg2r'