version: '3'

services:
  compute:
    build: ../compute
    restart: unless-stopped
    depends_on:
      - auth
      - manager
    environment:
      TOKEN: 'Kq5AfYtpYkcGbPnm0z2I_SIRGRem-zKmXA5rnPguUIB7y2DNQTW1KIYouV9IaHH6'

  auth:
    build: ../auth
    restart: unless-stopped
    environment:
      USER_TOKEN: 'DrERUGbWdDltQmkii0Mswney_dgDnUKFAwMC-TYB-C2zMnOuQeHgPtsHhBWzgoIg'

  manager:
    build: ../manager
    restart: unless-stopped
    depends_on:
      - auth
    environment:
      TOKEN: '3gEy0rWMRqXfJw9aLKzzSuhXggxGTLL4bYsTt-VdmFcmOWQ_ZCwTswvZM6kNVg2r'