name: auth

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 auth/*.py

  bandit:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run bandit
      run: |
        bandit -r auth/*.py || true

  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: chelsea486mhz
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:auth"
        push: true
        tags: chelsea486mhz/stargazer-auth:latest