name: manager

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r manager/requirements.txt
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 manager/*.py

  bandit:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r manager/requirements.txt
        pip install bandit

    - name: Run bandit
      run: |
        bandit -r manager/*.py || true

  publish:
    needs: [flake8, bandit]
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: chelsea486mhz
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:manager"
        push: true
        tags: chelsea486mhz/stargazer-manager:latest